# The company name - used for SSL certificates, and in srvious other places
COMPANY_NAME: "Example Com"

# The Country Name to use for SSL Certificates
SSL_COUNTRY_NAME: "US"

# The State Name to use for SSL Certificates
SSL_STATE_NAME: "Several"

# The Locality Name for SSL - typically, the city
SSL_LOCALITY_NAME: "Locality"

# What department?
SSL_ORGANIZATIONAL_UNIT_NAME: "Operations"

# The SSL contact email address
SSL_EMAIL_ADDRESS: "ops@your-app-name.com"
